'use client';

import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ShoppingCartProvider from './context/ShoppingCartContext';
import StyledComponentsRegistry from './lib/registry';
import Header from '@components/organisms/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Store App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactElement }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Header />
          {/* _app.tsx대신 최상위 layout.tsx에서 Provider를 감싼다. */}
          <ShoppingCartProvider>{children}</ShoppingCartProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
